version: '3'
services:
  keybout-backend:
    image: keybout-backend:v1.0
    container_name: keybout_backend
    ports:
      - 8080:8080
    networks:
      - keybout
  keybout-frontend:
    image: keybout-frontend:v1.0
    container_name: keybout_frontend
    ports:
      - 3000:80
    networks:
      - keybout
networks:
  keybout:
    external:
      name: keybout-network